INSTALL_DIR=${WORKSPACE}/BUILDS/volumedriver-buildtools-${BUILDTOOLS_VERSION?}
SOURCES_DIR=${WORKSPACE}/BUILDS/volumedriver-buildtools/sources
PREFIX=${INSTALL_DIR?}/rtchecked
BUILD_NUM_PROCESSES=4
PYTHON_VERSION=2.7
